# Generated by Django 3.2.5 on 2021-10-08 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_recipe_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='rating_average',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='review_count',
        ),
    ]
