# Generated by Django 3.2.8 on 2021-11-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_history_content_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ('-viewed_on',), 'verbose_name_plural': 'Histories'},
        ),
        migrations.AddField(
            model_name='history',
            name='username',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
