# Generated by Django 3.2.8 on 2021-11-26 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20211125_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='username',
        ),
    ]
