# Generated by Django 3.2.8 on 2022-01-04 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0093_alter_novelchapter_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0010_remove_history_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryNovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_on', models.DateTimeField(auto_now_add=True)),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.novel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
