# Generated by Django 3.2.5 on 2021-09-26 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0002_auto_20210925_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='update',
            new_name='comment',
        ),
    ]
