# Generated by Django 3.2.5 on 2021-09-26 03:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('novels', '0004_novelchapter_reply_comment_reply_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='updates', to=settings.AUTH_USER_MODEL),
        ),
    ]
