# Generated by Django 3.2.5 on 2021-09-28 01:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('novels', '0009_reply_review_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='novels', to=settings.AUTH_USER_MODEL),
        ),
    ]
