# Generated by Django 3.2.5 on 2021-09-28 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0010_novel_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='sumary',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
