# Generated by Django 3.2.5 on 2021-09-28 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('novels', '0011_alter_novel_sumary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novel',
            name='user',
        ),
        migrations.AddField(
            model_name='novel',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
