# Generated by Django 3.2.5 on 2021-09-28 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0012_auto_20210927_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novel',
            name='added_by',
        ),
    ]
