# Generated by Django 3.2.5 on 2021-09-29 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0014_auto_20210928_2305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='novel',
        ),
    ]
