# Generated by Django 3.2.5 on 2021-09-29 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0015_rename_comment_comment_novel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255, null=True)),
                ('novel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='novels.novel')),
            ],
        ),
    ]
