# Generated by Django 3.2.5 on 2021-09-30 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0018_auto_20210929_2029'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
