# Generated by Django 3.2.5 on 2021-10-01 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('novels', '0019_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply_comment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_comments', to='novels.comment'),
        ),
        migrations.AlterField(
            model_name='reply_comment',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reply_comments', to='profiles.profile'),
        ),
    ]
