# Generated by Django 3.2.5 on 2021-10-02 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0020_auto_20210930_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('public', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='InterestSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interests', models.ManyToManyField(related_name='interest_sets', to='novels.Interest')),
            ],
        ),
    ]
