# Generated by Django 3.2.5 on 2021-10-02 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0021_interest_interestset'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='interest_set',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='novels.interestset'),
        ),
    ]
