# Generated by Django 3.2.5 on 2021-10-02 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0022_novel_interest_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novel',
            name='interest_set',
        ),
        migrations.AddField(
            model_name='novel',
            name='interest_set',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='profiles', to='novels.Interest'),
        ),
    ]
