# Generated by Django 3.2.5 on 2021-10-02 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0024_auto_20211001_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='interest',
            field=models.ManyToManyField(blank=True, default=None, related_name='profiles', to='novels.Interest'),
        ),
    ]
