# Generated by Django 3.2.5 on 2021-10-05 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0025_alter_novel_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='interest',
            field=models.ManyToManyField(blank=True, default=None, related_name='interest', to='novels.Interest'),
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('novel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='novels.novel')),
            ],
        ),
    ]
