# Generated by Django 3.2.5 on 2021-10-05 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0027_auto_20211005_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='novel',
            field=models.ManyToManyField(related_name='library', to='novels.Novel'),
        ),
    ]
