# Generated by Django 3.2.5 on 2021-10-05 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0028_alter_library_novel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Library',
        ),
    ]
