# Generated by Django 3.2.5 on 2021-10-07 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('novels', '0031_library_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='library',
            old_name='novel',
            new_name='novels',
        ),
        migrations.AlterField(
            model_name='library',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_librarys', to=settings.AUTH_USER_MODEL),
        ),
    ]
