# Generated by Django 3.2.5 on 2021-10-07 00:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('novels', '0032_auto_20211006_2007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='library',
            options={'verbose_name_plural': 'Favorites Librarys'},
        ),
        migrations.RemoveField(
            model_name='library',
            name='novels',
        ),
        migrations.RemoveField(
            model_name='library',
            name='profile',
        ),
        migrations.AddField(
            model_name='library',
            name='novelss',
            field=models.ManyToManyField(blank=True, related_name='products', to='novels.Novel'),
        ),
        migrations.AlterField(
            model_name='library',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
