# Generated by Django 3.2.5 on 2021-10-07 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0033_auto_20211006_2023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='library',
            old_name='novelss',
            new_name='products',
        ),
    ]
