# Generated by Django 3.2.5 on 2021-10-07 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('novels', '0034_rename_novelss_library_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='products',
        ),
        migrations.AddField(
            model_name='library',
            name='novels',
            field=models.ManyToManyField(related_name='novels', to='novels.Novel'),
        ),
        migrations.AlterField(
            model_name='library',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_novels', to=settings.AUTH_USER_MODEL),
        ),
    ]
