# Generated by Django 3.2.5 on 2021-10-07 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0035_auto_20211007_1532'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Library',
        ),
    ]
