# Generated by Django 3.2.5 on 2021-10-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0039_alter_novelchapter_novel'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='novel_views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
