# Generated by Django 3.2.5 on 2021-10-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0040_novel_novel_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
