# Generated by Django 3.2.5 on 2021-10-10 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('novels', '0041_review_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interestset',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='novel',
            name='interest',
        ),
        migrations.AddField(
            model_name='novel',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='novels', to='tags.Tag'),
        ),
        migrations.DeleteModel(
            name='Interest',
        ),
        migrations.DeleteModel(
            name='InterestSet',
        ),
    ]
