# Generated by Django 3.2.5 on 2021-10-11 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('novels', '0042_auto_20211010_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='posts', to='categories.Category'),
        ),
    ]
