# Generated by Django 3.2.5 on 2021-10-11 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0043_novel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='novel_views',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
