# Generated by Django 3.2.5 on 2021-10-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_remove_category_description'),
        ('novels', '0044_alter_novel_novel_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='update_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='novel',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='posts', to='categories.Category'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='novel_views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
