# Generated by Django 3.2.5 on 2021-10-14 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0046_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
