# Generated by Django 3.2.5 on 2021-10-14 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0047_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='reply_comment',
            name='reply',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='reply_review',
            name='reply',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(max_length=255),
        ),
    ]
