# Generated by Django 3.2.5 on 2021-10-15 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0049_novel_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novel',
            name='rank',
        ),
    ]
