# Generated by Django 3.2.5 on 2021-10-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0052_auto_20211015_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AlterField(
            model_name='status',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
