# Generated by Django 3.2.5 on 2021-10-15 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0053_auto_20211015_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
