# Generated by Django 3.2.5 on 2021-10-16 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0055_novel_average'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='novel_views',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
