# Generated by Django 3.2.5 on 2021-10-16 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0056_alter_novel_novel_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='average',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True),
        ),
    ]
