# Generated by Django 3.2.5 on 2021-10-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0057_alter_novel_average'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
