# Generated by Django 3.2.5 on 2021-10-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0058_novel_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='rank',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
