# Generated by Django 3.2.8 on 2021-10-21 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0060_alter_novel_rank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='novel',
            options={'verbose_name_plural': 'Novels'},
        ),
    ]
