# Generated by Django 3.2.8 on 2021-10-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0061_alter_novel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='rank',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
