# Generated by Django 3.2.8 on 2021-11-25 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0062_alter_novel_rank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='novelchapter',
            options={'ordering': ('created_at',)},
        ),
    ]
