# Generated by Django 3.2.8 on 2021-12-09 01:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('novels', '0063_alter_novelchapter_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novel',
            name='likes',
        ),
        migrations.AddField(
            model_name='novel',
            name='book_marked',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
