# Generated by Django 3.2.8 on 2021-12-11 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0064_auto_20211208_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='novelchapter',
            name='slug',
            field=models.SlugField(max_length=100, null=True),
        ),
    ]
