# Generated by Django 3.2.8 on 2021-12-14 19:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('novels', '0066_alter_comment_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='book_marked',
            field=models.ManyToManyField(blank=True, related_name='book_marked', to=settings.AUTH_USER_MODEL),
        ),
    ]
