# Generated by Django 3.2.8 on 2021-12-14 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0067_alter_novel_book_marked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='author_novel', to='novels.authors'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='status_novel', to='novels.status'),
        ),
    ]
