# Generated by Django 3.2.8 on 2021-12-14 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0068_auto_20211214_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='novel_views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
