# Generated by Django 3.2.8 on 2021-12-15 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0070_auto_20211214_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(max_length=450),
        ),
    ]
