# Generated by Django 3.2.8 on 2021-12-15 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0071_alter_review_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(max_length=660),
        ),
    ]
