# Generated by Django 3.2.8 on 2021-12-18 22:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0072_alter_review_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='average',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
