# Generated by Django 3.2.8 on 2021-12-30 18:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('novels', '0076_novelchapter_is_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novelchapter',
            name='is_seen',
        ),
        migrations.AddField(
            model_name='novelchapter',
            name='user_seen',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
