# Generated by Django 3.2.8 on 2021-12-30 18:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('novels', '0077_auto_20211230_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novelchapter',
            name='user_seen',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
