# Generated by Django 3.2.8 on 2021-12-30 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0079_alter_novelchapter_user_seen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='novelchapter',
            old_name='user_seen',
            new_name='user_seens',
        ),
    ]
