# Generated by Django 3.2.8 on 2021-12-30 18:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('novels', '0080_rename_user_seen_novelchapter_user_seens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novelchapter',
            name='user_seens',
            field=models.ManyToManyField(blank=True, related_name='user_seen_chapters', to=settings.AUTH_USER_MODEL),
        ),
    ]
