# Generated by Django 3.2.8 on 2022-01-01 16:40

from django.conf import settings
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('novels', '0081_alter_novelchapter_user_seens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novelchapter',
            name='user_seens',
            field=models.ManyToManyField(blank=True, default=users.models.CustomUser, related_name='user_seen_chapters', to=settings.AUTH_USER_MODEL),
        ),
    ]
