# Generated by Django 3.2.8 on 2022-01-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0082_alter_novelchapter_user_seens'),
    ]

    operations = [
        migrations.AddField(
            model_name='novelchapter',
            name='number',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
