# Generated by Django 3.2.8 on 2022-01-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0083_novelchapter_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
