# Generated by Django 3.2.8 on 2022-01-03 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('novels', '0084_library_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.IntegerField(choices=[(1, 'Updated'), (2, 'Completed'), (3, 'Favorites'), (4, 'All')])),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('novel_library', models.ManyToManyField(blank=True, related_name='library_novels', through='novels.LibraryModel', to='novels.Novel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='librarymodel',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.userlibrary'),
        ),
        migrations.AddField(
            model_name='librarymodel',
            name='novel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_novel', to='novels.novel'),
        ),
    ]
