# Generated by Django 3.2.8 on 2022-01-03 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0085_auto_20220103_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlibrary',
            name='novel_library',
        ),
        migrations.RemoveField(
            model_name='userlibrary',
            name='user',
        ),
        migrations.DeleteModel(
            name='LibraryModel',
        ),
        migrations.DeleteModel(
            name='UserLibrary',
        ),
    ]
