# Generated by Django 3.2.8 on 2022-01-03 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0086_auto_20220103_1721'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Library',
        ),
    ]
