# Generated by Django 3.2.8 on 2022-01-03 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('novels', '0087_delete_library'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Favorites Librarys',
            },
        ),
        migrations.CreateModel(
            name='LibraryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.IntegerField(choices=[(1, 'Updated'), (2, 'Completed'), (3, 'Favorites'), (4, 'All')])),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.library')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_novel', to='novels.novel')),
            ],
        ),
        migrations.AddField(
            model_name='library',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='products', through='novels.LibraryModel', to='novels.Novel'),
        ),
        migrations.AddField(
            model_name='library',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
