# Generated by Django 3.2.8 on 2022-01-03 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0089_auto_20220103_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarymodel',
            name='option',
            field=models.IntegerField(blank=True, choices=[(1, 'Updated'), (2, 'Completed'), (3, 'Favorites'), (4, 'All')], null=True),
        ),
    ]
