# Generated by Django 3.2.8 on 2022-01-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0092_alter_librarymodel_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novelchapter',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
