# Generated by Django 3.2.8 on 2022-01-06 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0093_alter_novelchapter_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librarymodel',
            name='option',
        ),
    ]
