# Generated by Django 3.2.8 on 2021-11-26 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novelnotifiactions',
            name='novel',
        ),
        migrations.AddField(
            model_name='novelnotifiactions',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='novelnotifiactions',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
