# Generated by Django 3.2.8 on 2021-11-26 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0063_alter_novelchapter_options'),
        ('notifications', '0002_auto_20211126_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novelnotifiactions',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='novelnotifiactions',
            name='object_id',
        ),
        migrations.AddField(
            model_name='novelnotifiactions',
            name='novel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='novels.novel'),
        ),
    ]
