# Generated by Django 3.2.8 on 2021-11-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20211126_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='novelnotifiactions',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
