# Generated by Django 3.2.8 on 2021-12-10 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_novelnotifiactions_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='novelnotifiactions',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
