# Generated by Django 3.2.8 on 2021-12-10 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_auto_20211210_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novelnotifiactions',
            name='uuid',
        ),
    ]
